<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>hlb</string>
   </array>
  <key>name</key>
  <string>hlb</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.hlb</string>
  <key>uuid</key>
  <string>88c38584-8b5f-45be-93a6-e2c9da5b6e3f</string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#common</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\bstring\b|\bint\b|\bbool\b|\bfs\b|\bgroup\b|\boption(?!::)\b|\boption::(?:copy|frontend|git|http|image|local|mkdir|mkfile|mount|rm|run|secret|ssh|template)\b)</string>
          <key>name</key>
          <string>entity.name.type.hlb</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b(import|export|from|binds|as|with|variadic)\b)</string>
          <key>name</key>
          <string>keyword.hlb</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\b[a-zA-Z_][a-zA-Z0-9]*\b)(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>variable.hlb</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.hlb</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#params</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hlb</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\))</string>
          <key>name</key>
          <string>invalid.hlb</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>((?:[\t\x{0020}]+)as(?:[\t\x{0020}]+))(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.hlb</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.hlb</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#params</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hlb</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\))</string>
          <key>name</key>
          <string>invalid.hlb</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hlb</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#block</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hlb</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\})</string>
          <key>name</key>
          <string>invalid.hlb</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b[a-zA-Z_][a-zA-Z0-9]*\b)</string>
          <key>name</key>
          <string>variable.hlb</string>
        </dict>
       </array>
    </dict>
    <key>binding</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b[a-zA-Z_][a-zA-Z0-9]*\b)((?:[\t\x{0020}]+))(\b[a-zA-Z_][a-zA-Z0-9]*\b)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>variable.language.hlb</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.hlb</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>variable.hlb</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>block</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#common</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((?:[\t\x{0020}]+)with(?:[\t\x{0020}]+))</string>
          <key>name</key>
          <string>keyword.hlb</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(as)((?:[\t\x{0020}]+))(\b[a-zA-Z_][a-zA-Z0-9]*\b)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.hlb</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.hlb</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>variable.hlb</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(binds)((?:[\t\x{0020}]+))(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.hlb</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.hlb</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.hlb</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#binding</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hlb</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\bstring\b|\bint\b|\bbool\b|\bfs\b|\bgroup\b|\boption(?!::)\b|\boption::(?:copy|frontend|git|http|image|local|mkdir|mkfile|mount|rm|run|secret|ssh|template)\b)((?:[\t\x{0020}]+))(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.hlb</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.hlb</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.hlb</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#block</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hlb</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b((?!(allowEmptyWildcard|allowNotFound|allowWildcard|cache|checksum|chmod|chown|contentsOnly|copy|createDestPath|createParents|createdTime|dir|dockerLoad|dockerPush|download|downloadDockerTarball|downloadOCITarball|downloadTarball|env|excludePatterns|filename|followPaths|followSymlinks|format|forward|frontend|gid|git|host|http|id|ignoreCache|image|includePatterns|input|insecure|keepGitDir|local|localEnv|localPaths|locked|mkdir|mkfile|mode|mount|network|node|opt|parallel|private|readonly|readonlyRootfs|resolve|rm|run|sandbox|scratch|secret|security|shared|sourcePath|ssh|stringField|target|template|tmpfs|uid|unix|unpack|unset|user|value)\b)[a-zA-Z_][a-zA-Z0-9]*\b))</string>
          <key>name</key>
          <string>variable.hlb</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b[a-zA-Z_][a-zA-Z0-9]*\b)</string>
          <key>name</key>
          <string>variable.language.hlb</string>
        </dict>
       </array>
    </dict>
    <key>common</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(#.*)</string>
          <key>name</key>
          <string>comment.hlb</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((\b(0(b|B|o|O|x|X)[a-fA-F0-9]+)\b)|(\b(0|[1-9][0-9]*)\b)|(\b(true|false)\b))</string>
          <key>name</key>
          <string>constant.hlb</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hlb</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>string.hlb</string>
          <key>end</key>
          <string>(&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hlb</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(&lt;&lt;[-\x{007e}]?)([A-Z]+)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hlb</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>constant.hlb</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>string.hlb</string>
          <key>end</key>
          <string>(\2)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.hlb</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>common__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>common__2</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>params</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(variadic)</string>
          <key>name</key>
          <string>keyword.hlb</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\bstring\b|\bint\b|\bbool\b|\bfs\b|\bgroup\b|\boption(?!::)\b|\boption::(?:copy|frontend|git|http|image|local|mkdir|mkfile|mount|rm|run|secret|ssh|template)\b)</string>
          <key>name</key>
          <string>entity.name.type.hlb</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b[a-zA-Z_][a-zA-Z0-9]*\b)</string>
          <key>name</key>
          <string>variable.hlb</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
