linters:
  enable-all: false
  disable-all: true
  enable:
    - depguard
    - gofmt
    - goimports
    - gosimple
    - ineffassign
    - misspell
    - exportloopref
    - typecheck
    - unconvert
    - unused

issues:
  exclude-use-default: false
