linters:
  enable-all: false
  disable-all: true
  enable:
    - deadcode
    - depguard
    - gofmt
    - goimports
    - gosimple
    - ineffassign
    - misspell
    - scopelint
    - structcheck
    - typecheck
    - unconvert
    - varcheck

issues:
  exclude-use-default: false
