// Code generated by builtingen /language/builtin.hlb /out/builtin.go; DO NOT EDIT.

package builtin

import "github.com/openllb/hlb/parser"

type BuiltinLookup struct {
	ByKind map[parser.Kind]LookupByKind
}

type LookupByKind struct {
	Func map[string]FuncLookup
}

type FuncLookup struct {
	Params  []*parser.Field
	Effects []*parser.Field
}

var (
	Lookup = BuiltinLookup{
		ByKind: map[parser.Kind]LookupByKind{
			parser.Filesystem: LookupByKind{
				Func: map[string]FuncLookup{
					"scratch": FuncLookup{
						Params:  []*parser.Field{},
						Effects: []*parser.Field{},
					},
					"image": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "ref", false),
						},
						Effects: []*parser.Field{},
					},
					"http": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "url", false),
						},
						Effects: []*parser.Field{},
					},
					"git": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "remote", false),
							parser.NewField(parser.Str, "ref", false),
						},
						Effects: []*parser.Field{},
					},
					"local": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "path", false),
						},
						Effects: []*parser.Field{},
					},
					"frontend": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "source", false),
						},
						Effects: []*parser.Field{},
					},
					"shell": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "arg", true),
						},
						Effects: []*parser.Field{},
					},
					"run": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "arg", true),
						},
						Effects: []*parser.Field{},
					},
					"env": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "key", false),
							parser.NewField(parser.Str, "value", false),
						},
						Effects: []*parser.Field{},
					},
					"dir": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "path", false),
						},
						Effects: []*parser.Field{},
					},
					"user": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "name", false),
						},
						Effects: []*parser.Field{},
					},
					"mkdir": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "path", false),
							parser.NewField(parser.Int, "filemode", false),
						},
						Effects: []*parser.Field{},
					},
					"mkfile": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "path", false),
							parser.NewField(parser.Int, "filemode", false),
							parser.NewField(parser.Str, "content", false),
						},
						Effects: []*parser.Field{},
					},
					"rm": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "path", false),
						},
						Effects: []*parser.Field{},
					},
					"copy": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Filesystem, "input", false),
							parser.NewField(parser.Str, "src", false),
							parser.NewField(parser.Str, "dst", false),
						},
						Effects: []*parser.Field{},
					},
					"dockerPush": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "ref", false),
						},
						Effects: []*parser.Field{
							parser.NewField(parser.Str, "digest", false),
						},
					},
					"dockerLoad": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "ref", false),
						},
						Effects: []*parser.Field{},
					},
					"download": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "localPath", false),
						},
						Effects: []*parser.Field{},
					},
					"downloadTarball": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "localPath", false),
						},
						Effects: []*parser.Field{},
					},
					"downloadOCITarball": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "localPath", false),
						},
						Effects: []*parser.Field{},
					},
					"downloadDockerTarball": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "localPath", false),
							parser.NewField(parser.Str, "ref", false),
						},
						Effects: []*parser.Field{},
					},
					"entrypoint": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "args", true),
						},
						Effects: []*parser.Field{},
					},
					"cmd": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "args", true),
						},
						Effects: []*parser.Field{},
					},
					"label": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "key", false),
							parser.NewField(parser.Str, "value", false),
						},
						Effects: []*parser.Field{},
					},
					"expose": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "ports", true),
						},
						Effects: []*parser.Field{},
					},
					"volumes": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "mountpoints", true),
						},
						Effects: []*parser.Field{},
					},
					"stopSignal": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "signal", false),
						},
						Effects: []*parser.Field{},
					},
				},
			},
			"group": LookupByKind{
				Func: map[string]FuncLookup{
					"parallel": FuncLookup{
						Params: []*parser.Field{
							parser.NewField("group", "groups", true),
						},
						Effects: []*parser.Field{},
					},
				},
			},
			"option::copy": LookupByKind{
				Func: map[string]FuncLookup{
					"followSymlinks": FuncLookup{
						Params:  []*parser.Field{},
						Effects: []*parser.Field{},
					},
					"contentsOnly": FuncLookup{
						Params:  []*parser.Field{},
						Effects: []*parser.Field{},
					},
					"unpack": FuncLookup{
						Params:  []*parser.Field{},
						Effects: []*parser.Field{},
					},
					"createDestPath": FuncLookup{
						Params:  []*parser.Field{},
						Effects: []*parser.Field{},
					},
					"allowWildcard": FuncLookup{
						Params:  []*parser.Field{},
						Effects: []*parser.Field{},
					},
					"allowEmptyWildcard": FuncLookup{
						Params:  []*parser.Field{},
						Effects: []*parser.Field{},
					},
					"chown": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "owner", false),
						},
						Effects: []*parser.Field{},
					},
					"chmod": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Int, "filemode", false),
						},
						Effects: []*parser.Field{},
					},
					"createdTime": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "created", false),
						},
						Effects: []*parser.Field{},
					},
				},
			},
			"option::frontend": LookupByKind{
				Func: map[string]FuncLookup{
					"input": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "key", false),
							parser.NewField(parser.Filesystem, "value", false),
						},
						Effects: []*parser.Field{},
					},
					"opt": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "key", false),
							parser.NewField(parser.Str, "value", false),
						},
						Effects: []*parser.Field{},
					},
				},
			},
			"option::git": LookupByKind{
				Func: map[string]FuncLookup{
					"keepGitDir": FuncLookup{
						Params:  []*parser.Field{},
						Effects: []*parser.Field{},
					},
				},
			},
			"option::http": LookupByKind{
				Func: map[string]FuncLookup{
					"checksum": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "digest", false),
						},
						Effects: []*parser.Field{},
					},
					"chmod": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Int, "filemode", false),
						},
						Effects: []*parser.Field{},
					},
					"filename": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "name", false),
						},
						Effects: []*parser.Field{},
					},
				},
			},
			"option::image": LookupByKind{
				Func: map[string]FuncLookup{
					"resolve": FuncLookup{
						Params:  []*parser.Field{},
						Effects: []*parser.Field{},
					},
				},
			},
			"option::local": LookupByKind{
				Func: map[string]FuncLookup{
					"includePatterns": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "pattern", true),
						},
						Effects: []*parser.Field{},
					},
					"excludePatterns": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "pattern", true),
						},
						Effects: []*parser.Field{},
					},
					"followPaths": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "path", true),
						},
						Effects: []*parser.Field{},
					},
				},
			},
			"option::localRun": LookupByKind{
				Func: map[string]FuncLookup{
					"ignoreError": FuncLookup{
						Params:  []*parser.Field{},
						Effects: []*parser.Field{},
					},
					"includeStderr": FuncLookup{
						Params:  []*parser.Field{},
						Effects: []*parser.Field{},
					},
					"onlyStderr": FuncLookup{
						Params:  []*parser.Field{},
						Effects: []*parser.Field{},
					},
					"shlex": FuncLookup{
						Params:  []*parser.Field{},
						Effects: []*parser.Field{},
					},
				},
			},
			"option::mkdir": LookupByKind{
				Func: map[string]FuncLookup{
					"createParents": FuncLookup{
						Params:  []*parser.Field{},
						Effects: []*parser.Field{},
					},
					"chown": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "owner", false),
						},
						Effects: []*parser.Field{},
					},
					"createdTime": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "created", false),
						},
						Effects: []*parser.Field{},
					},
				},
			},
			"option::mkfile": LookupByKind{
				Func: map[string]FuncLookup{
					"chown": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "owner", false),
						},
						Effects: []*parser.Field{},
					},
					"createdTime": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "created", false),
						},
						Effects: []*parser.Field{},
					},
				},
			},
			"option::mount": LookupByKind{
				Func: map[string]FuncLookup{
					"readonly": FuncLookup{
						Params:  []*parser.Field{},
						Effects: []*parser.Field{},
					},
					"tmpfs": FuncLookup{
						Params:  []*parser.Field{},
						Effects: []*parser.Field{},
					},
					"sourcePath": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "path", false),
						},
						Effects: []*parser.Field{},
					},
					"cache": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "cacheid", false),
							parser.NewField(parser.Str, "sharingmode", false),
						},
						Effects: []*parser.Field{},
					},
				},
			},
			"option::rm": LookupByKind{
				Func: map[string]FuncLookup{
					"allowNotFound": FuncLookup{
						Params:  []*parser.Field{},
						Effects: []*parser.Field{},
					},
					"allowWildcard": FuncLookup{
						Params:  []*parser.Field{},
						Effects: []*parser.Field{},
					},
				},
			},
			"option::run": LookupByKind{
				Func: map[string]FuncLookup{
					"readonlyRootfs": FuncLookup{
						Params:  []*parser.Field{},
						Effects: []*parser.Field{},
					},
					"env": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "key", false),
							parser.NewField(parser.Str, "value", false),
						},
						Effects: []*parser.Field{},
					},
					"dir": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "path", false),
						},
						Effects: []*parser.Field{},
					},
					"user": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "name", false),
						},
						Effects: []*parser.Field{},
					},
					"ignoreCache": FuncLookup{
						Params:  []*parser.Field{},
						Effects: []*parser.Field{},
					},
					"network": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "networkmode", false),
						},
						Effects: []*parser.Field{},
					},
					"security": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "securitymode", false),
						},
						Effects: []*parser.Field{},
					},
					"shlex": FuncLookup{
						Params:  []*parser.Field{},
						Effects: []*parser.Field{},
					},
					"host": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "hostname", false),
							parser.NewField(parser.Str, "address", false),
						},
						Effects: []*parser.Field{},
					},
					"ssh": FuncLookup{
						Params:  []*parser.Field{},
						Effects: []*parser.Field{},
					},
					"forward": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "src", false),
							parser.NewField(parser.Str, "dest", false),
						},
						Effects: []*parser.Field{},
					},
					"secret": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "localPath", false),
							parser.NewField(parser.Str, "mountPoint", false),
						},
						Effects: []*parser.Field{},
					},
					"mount": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Filesystem, "input", false),
							parser.NewField(parser.Str, "mountPoint", false),
						},
						Effects: []*parser.Field{
							parser.NewField(parser.Filesystem, "target", false),
						},
					},
				},
			},
			"option::secret": LookupByKind{
				Func: map[string]FuncLookup{
					"uid": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Int, "id", false),
						},
						Effects: []*parser.Field{},
					},
					"gid": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Int, "id", false),
						},
						Effects: []*parser.Field{},
					},
					"mode": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Int, "filemode", false),
						},
						Effects: []*parser.Field{},
					},
					"includePatterns": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "pattern", true),
						},
						Effects: []*parser.Field{},
					},
					"excludePatterns": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "pattern", true),
						},
						Effects: []*parser.Field{},
					},
				},
			},
			"option::ssh": LookupByKind{
				Func: map[string]FuncLookup{
					"target": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "mountPoint", false),
						},
						Effects: []*parser.Field{},
					},
					"localPaths": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "path", true),
						},
						Effects: []*parser.Field{},
					},
					"uid": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Int, "id", false),
						},
						Effects: []*parser.Field{},
					},
					"gid": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Int, "id", false),
						},
						Effects: []*parser.Field{},
					},
					"mode": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Int, "filemode", false),
						},
						Effects: []*parser.Field{},
					},
				},
			},
			"option::template": LookupByKind{
				Func: map[string]FuncLookup{
					"stringField": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "name", false),
							parser.NewField(parser.Str, "value", false),
						},
						Effects: []*parser.Field{},
					},
				},
			},
			parser.Str: LookupByKind{
				Func: map[string]FuncLookup{
					"format": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "formatString", false),
							parser.NewField(parser.Str, "values", true),
						},
						Effects: []*parser.Field{},
					},
					"localArch": FuncLookup{
						Params:  []*parser.Field{},
						Effects: []*parser.Field{},
					},
					"localCwd": FuncLookup{
						Params:  []*parser.Field{},
						Effects: []*parser.Field{},
					},
					"localEnv": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "key", false),
						},
						Effects: []*parser.Field{},
					},
					"localOs": FuncLookup{
						Params:  []*parser.Field{},
						Effects: []*parser.Field{},
					},
					"localRun": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "command", false),
							parser.NewField(parser.Str, "args", true),
						},
						Effects: []*parser.Field{},
					},
					"manifest": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "ref", false),
						},
						Effects: []*parser.Field{
							parser.NewField(parser.Str, "digest", false),
						},
					},
					"template": FuncLookup{
						Params: []*parser.Field{
							parser.NewField(parser.Str, "text", false),
						},
						Effects: []*parser.Field{},
					},
				},
			},
		},
	}
)
